
import Foundation

struct CurrencyInfo {
    
    var filteredCurrencies = [String]()
    
    let currencyModels = [CurrencyModel(title: "Popular", currency: ["USD - United States Dollar", "EUR - Euro", "UAH - Ukrainian Hryvnia"]),
                         CurrencyModel(title: "A", currency: ["AED - United Arab Emirates Dirham",
                                                              "AFN - Afghan Afghani",
                                                              "ALL - Albanian Lek",
                                                              "AMD - Armenian Dram",
                                                              "ANG - Netherlands Antillean Guilder",
                                                              "AOA - Angolan Kwanza",
                                                              "ARS - Argentine Peso",
                                                              "AUD - Australian Dollar",
                                                              "AWG - Aruban Florin",
                                                              "AZN - Azerbaijani Manat"]),
                         CurrencyModel(title: "B", currency: ["BAM - Bosnia-Herzegovina Convertible Mark",
                                                              "BBD - Barbadian Dollar",
                                                              "BDT - Bangladeshi Taka",
                                                              "BGN - Bulgarian Lev",
                                                              "BHD - Bahraini Dinar",
                                                              "BIF - Burundian Franc",
                                                              "BMD - Bermudan Dollar",
                                                              "BND - Brunei Dollar",
                                                              "BOB - Bolivian Boliviano",
                                                              "BRL - Brazilian Real",
                                                              "BSD - Bahamian Dollar",
                                                              "BTC - Bitcoin",
                                                              "BTN - Bhutanese Ngultrum",
                                                              "BWP - Botswanan Pula",
                                                              "BZD - Belize Dollar"]),
                         CurrencyModel(title: "C", currency: ["CAD - Canadian Dollar",
                                                              "CDF - Congolese Franc",
                                                              "CHF - Swiss Franc",
                                                              "CLF - Chilean Unit of Account (UF)",
                                                              "CLP - Chilean Peso",
                                                              "CNY - Chinese Yuan",
                                                              "COP - Colombian Peso",
                                                              "CRC - Costa Rican",
                                                              "CUC - Cuban Convertible Peso",
                                                              "CUP - Cuban Peso",
                                                              "CVE - Cape Verdean Escudo",
                                                              "CZK - Czech Republic Koruna"]),
                         CurrencyModel(title: "D", currency: ["DJF - Djiboutian Franc",
                                                              "DKK - Danish Krone",
                                                              "DOP - Dominican Peso",
                                                              "DZD - Algerian Dinar"]),
                         CurrencyModel(title: "E", currency: ["EGP - Egyptian Pound",
                                                              "ERN - Eritrean Nakfa",
                                                              "ETB - Ethiopian Birr",
                                                              "EUR - Euro"]),
                         CurrencyModel(title: "F", currency: ["FJD - Fijian Dollar",
                                                              "FKP - Falkland Islands Pound"]),
                         CurrencyModel(title: "G", currency: ["GBP - British Pound Sterling",
                                                              "GEL - Georgian Lari",
                                                              "GGP - Guernsey Pound",
                                                              "GHS - Ghanaian Cedi",
                                                              "GIP - Gibraltar Pound",
                                                              "GMD - Gambian Dalasi",
                                                              "GNF - Guinean Franc",
                                                              "GTQ - Guatemalan Quetzal",
                                                              "GYD - Guyanaese Dollar"]),
                         CurrencyModel(title: "H", currency: ["HKD - Hong Kong Dollar",
                                                              "HNL - Honduran Lempira",
                                                              "HRK - Croatian Kuna",
                                                              "HTG - Haitian Gourde",
                                                              "HUF - Hungarian Forint"]),
                         CurrencyModel(title: "I", currency: ["IDR - Indonesian Rupiah",
                                                              "ILS - Israeli New Sheqel",
                                                              "IMP - Manx pound",
                                                              "INR - Indian Rupee",
                                                              "IQD - Iraqi Dinar",
                                                              "IRR - Iranian Rial",
                                                              "ISK - Icelandic Krona"]),
                         CurrencyModel(title: "J", currency: ["JEP - Jersey Pound",
                                                              "JMD - Jamaican Dollar",
                                                              "JOD - Jordanian Dinar",
                                                              "JPY - Japanese Yen"]),
                         CurrencyModel(title: "K", currency: ["KES - Kenyan Shilling",
                                                              "KGS - Kyrgystani Som",
                                                              "KHR - Cambodian Riel",
                                                              "KMF - Comorian Franc",
                                                              "KPW - North Korean Won",
                                                              "KRW - South Korean Won",
                                                              "KWD - Kuwaiti Dinar",
                                                              "KYD - Cayman Islands Dollar",
                                                              "KZT - Kazakhstani Tenge"]),
                         CurrencyModel(title: "L", currency: ["LAK - Laotian Kip",
                                                              "LBP - Lebanese Pound",
                                                              "LKR - Sri Lankan Rupee",
                                                              "LRD - Liberian Dollar",
                                                              "LSL - Lesotho Loti",
                                                              "LYD - Libyan Dinar"]),
                         CurrencyModel(title: "M", currency: ["MAD - Moroccan Dirham",
                                                              "MDL - Moldovan Leu",
                                                              "MGA - Malagasy Ariary",
                                                              "MKD - Macedonian Denar",
                                                              "MMK - Myanma Kyat",
                                                              "MNT - Mongolian Tugrik",
                                                              "MOP - Macanese Pataca",
                                                              "MUR - Mauritian Rupee",
                                                              "MVR - Maldivian Rufiyaa",
                                                              "MWK - Malawian Kwacha",
                                                              "MXN - Mexican Peso",
                                                              "MYR - Malaysian Ringgit",
                                                              "MZN - Mozambican Metical"]),
                         CurrencyModel(title: "N", currency: ["NAD - Namibian Dollar",
                                                              "NGN - Nigerian Naira",
                                                              "NIO - Nicaraguan Cordoba",
                                                              "NOK - Norwegian Krone",
                                                              "NPR - Nepalese Rupee",
                                                              "NZD - New Zealand Dollar"]),
                         CurrencyModel(title: "O", currency: ["OMR - Omani Rial"]),
                         CurrencyModel(title: "P", currency: ["PAB - Panamanian Balboa",
                                                              "PEN - Peruvian Nuevo Sol",
                                                              "PGK - Papua New Guinean Kina",
                                                              "PHP - Philippine Peso",
                                                              "PKR - Pakistani Rupee",
                                                              "PLN - Polish Zloty",
                                                              "PYG - Paraguayan Guarani"]),
                         CurrencyModel(title: "Q", currency: ["QAR - Qatari Rial"]),
                         CurrencyModel(title: "R", currency: ["RON - Romanian Leu",
                                                              "RSD - Serbian Dinar",
                                                              "RUB - Russian Ruble",
                                                              "RWF - Rwandan Franc"]),
                         CurrencyModel(title: "S", currency: ["SAR - Saudi Riyal",
                                                              "SBD - Solomon Islands Dollar",
                                                              "SCR - Seychellois Rupee",
                                                              "SDG - Sudanese Pound",
                                                              "SEK - Swedish Krona",
                                                              "SGD - Singapore Dollar",
                                                              "SHP - Saint Helena Pound",
                                                              "SLL - Sierra Leonean Leone",
                                                              "SOS - Somali Shilling",
                                                              "SRD - Surinamese Dollar",
                                                              "STD - Sao Tome and Principe Dobra",
                                                              "SVC - Salvadoran Colon",
                                                              "SYP - Syrian Pound",
                                                              "SZL - Swazi Lilangeni"]),
                         CurrencyModel(title: "T", currency: ["THB - Thai Baht",
                                                              "TJS - Tajikistani Somoni",
                                                              "TMT - Turkmenistani Manat",
                                                              "TND - Tunisian Dinar",
                                                              "TOP - Tongan Pa'anga",
                                                              "TRY - Turkish Lira",
                                                              "TTD - Trinidad and Tobago Dollar",
                                                              "TWD - New Taiwan Dollar",
                                                              "TZS - Tanzanian Shilling"]),
                         CurrencyModel(title: "U", currency: ["UAH - Ukrainian Hryvnia",
                                                              "UGX - Ugandan Shilling",
                                                              "USD - United States Dollar",
                                                              "UYU - Uruguayan Peso",
                                                              "UZS - Uzbekistan Som"]),
                         CurrencyModel(title: "V", currency: ["VES - Sovereign Bolivar",
                                                              "VND - Vietnamese Dong",
                                                              "VUV - Vanuatu Vatu"]),
                         CurrencyModel(title: "W", currency: ["WST - Samoan Tala"]),
                         CurrencyModel(title: "X", currency: ["XAF - CFA Franc BEAC",
                                                              "XAG - Silver (troy ounce)",
                                                              "XAU - Gold (troy ounce)",
                                                              "XCD - East Caribbean Dollar",
                                                              "XDR - Special Drawing Rights",
                                                              "XOF - CFA Franc BCEAO",
                                                              "XPF - CFP Franc"]),
                         CurrencyModel(title: "Y", currency: ["YER - Yemeni Rial"]),
                         CurrencyModel(title: "Z", currency: ["ZAR - South African Rand",
                                                              "ZMW - Zambian Kwacha",
                                                              "ZWL - Zimbabwean Dollar"])]
}
